actors:
  luccafort:
    image_url: /images/actors/luccafort.jpg
    name: luccafort
    url: http://twitter.com/luccafort
author: luccafort
description: 雑話を話します
description_long: TLなどで話題になったTechなトピックや身近な話しなんかを独白として話していくpodcastです。
email: muspellsheim1985@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: snobbyfm
itunes_podcast_url:
keywords: tech,snobbyfm
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: snobby.fm
url: https://houka-go-projects.github.io/
